apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  DB_NAME: ZGphbmdvX2xvY2FsaG9zdA==
  DB_USER: cm9vdA==
  DB_PASSWORD: U291cmF2QDI0
  DJANGO_SECRET_KEY: JihjMSkqcThjJTF1cUAyIStkejYhNWl3cj03YmRjbyp2KiFeb2dwcHReMXMzKzBncTQ=