apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_DEBUG: "False"
  MYSQL_HOST: "souravdb"
  MYSQL_PORT: "3306"
  DATABASE_ENGINE: "django.db.backends.mysql"