apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: django-route
spec:
  to:
    kind: Service
    name: django-service
  port:
    targetPort: 8001   # âœ… corrected to match Service + Gunicorn port
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
