apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tictactoe-ingress   # name can be "ingress"
spec:
  to:
    kind: Service
    name: tictactoe-service
  port:
    targetPort: 8000
  tls:
  termination: edge
  insecureEdgeTerminationPolicy: Redirect
  
